global:
  domain: argocd.local

configs:
  cm:
    "timeout.reconciliation": 30s
    "timeout.reconciliation.jitter": 0s
    "timeout.hard.reconciliation": 30s

  params:
    "server.insecure": true

controller:
  extraArgs:
    - --app-resync
    - "30"
    - --app-hard-resync
    - "30"
    - --app-resync-jitter
    - "0"

server:
  ingress:
    enabled: true
    controller: generic
    ingressClassName: traefik
    hostname: argocd.local
    path: /
    pathType: Prefix
    tls: false
    annotations: {}