global:
  hosts:
    domain: local
    https: false

  ingress:
    enabled: true
    class: traefik
    configureCertmanager: false
    tls:
      enabled: false

  gatewayApi:
    enabled: false

  kas:
    enabled: false

  pages:
    enabled: false

  registry:
    enabled: false

  appConfig:
    initialRootPassword:
      secret: gitlab-gitlab-initial-root-password
      key: password

installCertmanager: false

nginx-ingress:
  enabled: false

gitlab-runner:
  install: false

prometheus:
  install: false

registry:
  enabled: false

postgresql:
  primary:
    persistence:
      size: 2Gi

redis:
  master:
    persistence:
      size: 2Gi

gitaly:
  persistence:
    size: 2Gi

minio:
  credentials:
    secret: gitlab-minio-secret
  persistence:
    size: 2Gi
