# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.boot_timeout = 600
  config.vm.box = "bento/ubuntu-24.04"

  NODES = [
    { 
      :hostname => "jmougelS",
      :ip => "192.168.56.110",
      :memory => "2048",
      :cpus => 1,
      :name => "jmougel",
      :script_path => "./scripts/install_server.sh",
    },
    { 
      :hostname => "jmougelSW",
      :ip => "192.168.56.111",
      :memory => "2048",
      :cpus => 1,
      :name => "klombard",
      :script_path => "./scripts/install_worker.sh",
    }
  ]

  NODES.each do |node|
    config.vm.define node[:hostname] do |s|
      s.vm.hostname = node[:hostname]
      s.vm.network "private_network", ip: node[:ip]

      s.vm.provider "virtualbox" do |vb|
        vb.memory = node[:memory]
        vb.cpus = node[:cpus]
        vb.name = node[:name]
      end

      s.vm.provision "shell", path: node[:script_path], run: "always"
    end
  end
end